// Generated by CoffeeScript 1.7.1
(function() {
  var module;

  module = angular.module('atns.ng.messages', ['ui.bootstrap', 'partials/confirm-dialog.html']);

  module.controller('ConfirmDialog', function($scope, $modalInstance, title, message, aktionOK) {
    $scope.title = title;
    $scope.message = message;
    $scope.aktionOK = aktionOK;
    $scope.ok = function() {
      return $modalInstance.close();
    };
    return $scope.cancel = function() {
      return $modalInstance.dismiss('cancel');
    };
  });

  module.run(function($rootScope, $modal) {
    return $rootScope.confirmDialog = function(title, message, aktionOK, action, args) {
      var dialog;
      dialog = $modal.open({
        templateUrl: 'partials/confirm-dialog.html',
        controller: 'ConfirmDialog',
        resolve: {
          title: function() {
            return title;
          },
          message: function() {
            return message;
          },
          aktionOK: function() {
            return aktionOK;
          }
        }
      });
      return dialog.result.then(function() {
        return action(args);
      });
    };
  });

  angular.module('partials/confirm-dialog.html', []).run(function($templateCache) {
    return $templateCache.put('partials/confirm-dialog.html', "<div class=\"modal-header\">\n    <button type=\"button\" class=\"close\" ng-click=\"cancel()\">×</button>\n    <h3>{{title}}</h3>\n</div>\n<div class=\"modal-body\">\n    <p>{{message}}</p>\n</div>\n<div class=\"modal-footer\">\n    <button class=\"btn btn-default btn-sm\" ng-click=\"cancel()\" tabindex=\"-1\">Abbrechen</button>\n    <button class=\"btn btn-warning btn-sm\" ng-click=\"ok()\">\n        {{aktionOK}}\n    </button>\n</div>");
  });

}).call(this);
