// Generated by CoffeeScript 1.7.1
(function() {
  var module;

  module = angular.module('atns.ng.messages', ['ui.bootstrap']);

  module.controller('ConfirmDialog', function($scope, $modalInstance, title, message, aktionOK) {
    $scope.title = title;
    $scope.message = message;
    $scope.aktionOK = aktionOK;
    $scope.ok = function() {
      return $modalInstance.close();
    };
    return $scope.cancel = function() {
      return $modalInstance.dismiss('cancel');
    };
  });

  module.run(function($rootScope, $modal) {
    return $rootScope.confirmDialog = function(title, message, aktionOK, action, args) {
      var dialog;
      dialog = $modal.open({
        templateUrl: 'partials/confirm-dialog.html',
        controller: 'ConfirmDialog',
        resolve: {
          title: function() {
            return title;
          },
          message: function() {
            return message;
          },
          aktionOK: function() {
            return aktionOK;
          }
        }
      });
      return dialog.result.then(function() {
        return action(args);
      });
    };
  });

}).call(this);
